version: '3.8'

services:
  app_version_control_service:
    container_name: app_version_control_service
    build:
      context: .
      dockerfile: Dockerfile
    hostname: app_version_control_service
    ports:
      - "3000:5001"
    # restart: always
