
export const DEVELOPMENT = 'development';
export const TEST = 'test';
export const PRODUCTION = 'production';

export const DATABASE_CONNECTION = 'DATABASE_CONNECTION'
export const USER_REPOSITORY = 'USER_REPOSITORY';

export const TESTING_REPOSITORY='TESTING_REPOSITORY'

export const VERSION_CONTROL_REPOSITORY='VERSION_CONTROL_REPOSITORY'
export const VERSION_CONTROL_HISTORY_REPOSITORY='VERSION_CONTROL_HISTORY_REPOSITORY'

export const SHEBA_MERCHANT_CUSTOMER_SUPPLIER_REPOSITORY ='SHEBA_MERCHANT_CUSTOMER_SUPPLIER_REPOSITORY'
export const SHEBA_TAGADA_SEND_HISTORY_REPOSITORY ='SHEBA_TAGADA_SEND_HISTORY_REPOSITORY'


